# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
author: Arthur
title: Arthur's Blog
subtitle: 'just a blog'
keywords:
timezone: ''
description: ''
language: zh-CN

# URL
url: https://arthur63.top/
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

# Directory
tag_dir: tags
i18n_dir: :lang
source_dir: source
public_dir: public
archive_dir: archives
category_dir: categories
code_dir: downloads/code
skip_render: []

# Writing
new_post_name: :title.md
default_layout: post
filename_case: 0
titlecase: false
render_drafts: false
relative_link: false
post_asset_folder: true
future: true
external_link:
  enable: true
  field: site
  exclude: ''

# Codeblock
syntax_highlighter: prismjs

highlight:
  enable: false
  line_number: true
  auto_detect: false
  line_threshold: 0
  tab_replace: '    '
  exclude_languages:
  wrap: true
  hljs: false

prismjs:
  enable: true
  preprocess: false
  line_number: true
  line_threshold: 0
  tab_replace: '    '

# Home page setting
index_generator:
  path: ''
  per_page: 10
  order_by: -updated

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
meta_generator: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude files
include:
exclude:
ignore:

# Theme
theme: next

# Search
search:
  path: search.json
  field: post
  format: html
  limit: 10000

# Markdown-it
markdown:
  plugins:
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-footnote

