# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
keywords:
timezone:
description:
author: Arthur
title: "Arthur's Blog"
subtitle: 'just a blog'
language: zh-CN

# URL
permalink: :title/
permalink_defaults:
url: https://arthur63.top/
pretty_urls:
  trailing_index: true
  trailing_html: true

# Directory
skip_render:
tag_dir: tags
i18n_dir: :lang
source_dir: source
public_dir: public
archive_dir: archives
category_dir: categories
code_dir: downloads/code

# Writing
future: true
titlecase: false
filename_case: 0
render_drafts: false
relative_link: false
default_layout: post
post_asset_folder: true
new_post_name: :title.md
external_link:
  enable: true
  field: site
  exclude: ''

# Codeblock
syntax_highlighter: prismjs

highlight:
  enable: false

prismjs:
  enable: true
  preprocess: false
  line_number: true
  line_threshold: 0
  tab_replace: '    '

# Home page setting
index_generator:
  path: ''
  per_page: 10
  order_by: -updated

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
meta_generator: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

# Pagination
per_page: 10
pagination_dir: page

# Include / Exclude files
include:
exclude:
ignore:

# Theme
theme: next

# Search
search:
  path: search.json
  field: post
  format: html
  limit: 10000

# Markdown-it
markdown:
  plugins:
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-footnote

