# ---------------------------------------------------------------
# Theme Core Configuration Settings
# ---------------------------------------------------------------

# Allow to cache content generation.
cache:
  enable: true

# Remove unnecessary files after hexo generate.
minify: true

# ---------------------------------------------------------------
# Scheme Settings
# ---------------------------------------------------------------

# Schemes
scheme: Gemini

# Dark Mode
darkmode: true

# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

favicon:
  small: /images/favicon-16x16-next.png
  medium: /images/favicon-32x32-next.png
  apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo.svg

# Custom Logo
custom_logo:

# Creative Commons 4.0 International License.
creative_commons:
  license: by-nc-sa
  size: small
  sidebar: false
  post: true
  language:

# Open graph settings
open_graph:
  enable: true
  options:

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  links: /links/ || fa fa-link

# Enable / Disable menu icons / item badges.
menu_settings:
  icons: true
  badges: true

# ---------------------------------------------------------------
# Sidebar Settings
# ---------------------------------------------------------------

sidebar:
  position: left
  display: post
  padding: 18
  offset: 12

# Sidebar Avatar
avatar:
  url: /images/avatar.png
  rounded: false
  rotated: false

# Posts / Categories / Tags in sidebar.
site_state: true

social_icons:
  enable: true
  icons_only: false
  transition: false

# Blog rolls
links_settings:
  icon: fa fa-globe
  layout: block

# Table of Contents in the Sidebar
toc:
  enable: true
  number: false
  wrap: false
  expand_all: false
  max_depth: 6


# ---------------------------------------------------------------
# Footer Settings
# ---------------------------------------------------------------

footer:
  icon:
    name: fa fa-heart
    animated: true
    color: "#ff0000"

  powered: true

# ---------------------------------------------------------------
# Post Settings
# ---------------------------------------------------------------

excerpt_description: true

# Read more button
read_more_btn: true

# Post meta display settings
post_meta:
  item_text: true
  created_at: true
  categories: true
  updated_at:
    enable: true
    another_day: true

# Post wordcount display settings
symbols_count_time:
  separated_meta: true
  item_text_total: false

# Post edit
post_edit:
  enable: true
  url: https://github.com/fanenr/blog/edit/master/source/

post_navigation: left

# ---------------------------------------------------------------
# Custom Page Settings
# ---------------------------------------------------------------

# TagCloud settings for tags page.
tagcloud:
  min: 12
  max: 30
  amount: 200
  orderby: name
  order: 1

# ---------------------------------------------------------------
# Misc Theme Settings
# ---------------------------------------------------------------

# Preload styles and preconnect CDN for fonts and plugins.
preconnect: true

# Set the text alignment in posts / pages.
text_align:
  desktop: justify
  mobile: justify

# Reduce padding / margin indents on devices with narrow width.
mobile_layout_economy: true

# Browser header panel color.
theme_color:
  light: "#222"
  dark: "#222"

# https://theme-next.js.org/highlight/
codeblock:
  theme:
    light: github
    dark: github-dark
    
  prism:
    light: prism-solarizedlight
    dark: prism-tomorrow
    
  copy_button:
    enable: true
    style: default
    
  fold:
    enable: true
    height: 500

back2top:
  enable: true
  sidebar: false
  scrollpercent: true

# GitHub banner.
github_banner:
  enable: true
  permalink: https://github.com/fanenr


# ---------------------------------------------------------------
# Font Settings
# ---------------------------------------------------------------

font:
  enable: true
  host:

  global:
    external: true
    family: Noto Sans SC
    size: 1

  title:
    external: true
    family:
    size:

  headings:
    external: true
    family:
    size:

  posts:
    external: true
    family:

  codes:
    external: true
    family: Roboto Mono

# ---------------------------------------------------------------
# Tags Settings
# ---------------------------------------------------------------

note:
  style: modern
  icons: false
  light_bg_offset: 0

# Tabs tag
tabs:
  sticky: true
  transition:
    tabs: false
    labels: true

# PDF tag
pdf:
  enable: true
  # Default height
  height: 500px

# Mermaid tag
mermaid:
  enable: true
  theme:
    light: default
    dark: dark

# WaveDrom tag
wavedrom:
  enable: true

# ---------------------------------------------------------------
# Math Formulas Render Support
# ---------------------------------------------------------------

math:
  every_page: false

  mathjax:
    enable: false
    tags: none

  katex:
    enable: false
    copy_tex: false

# ---------------------------------------------------------------
# External Libraries
# ---------------------------------------------------------------

# Pjax
pjax: true

# FancyBox
fancybox: true

# Vanilla JavaScript plugin for lazyloading images.
lazyload: true

# Prefetch links based on what is in the user's viewport.
quicklink:
  enable: true

  home: false
  archive: false

  delay: true
  timeout: 3000
  priority: true

# ---------------------------------------------------------------
# Animation Settings
# ---------------------------------------------------------------

motion:
  enable: true
  async: false
  transition:
    menu_item: fadeInDown
    post_block: fadeIn
    post_header: fadeInDown
    post_body: fadeInDown
    coll_header: fadeInLeft
    sidebar: fadeInUp

# ---------------------------------------------------------------
# Comments Settings
# ---------------------------------------------------------------

# Multiple Comment System Support
comments:
  style: tabs
  active: disqus
  storage: true
  lazyload: false
  nav:

# Waline Config File
waline:
  enable: true
  reaction: true
  dark: auto

  serverURL: https://waline.arthur63.cc/
  libUrl: https://unpkg.com/@waline/client@v2/dist/waline.js
  cssUrl: https://unpkg.com/@waline/client@v2/dist/waline.css

  lang: zh-CN
  login: enable
  pageSize: 10
  pageview: true
  commentCount: true

  locale:
    placeholder: Welcome to comment

# Disqus
disqus:
  enable: false
  shortname: arthur63
  count: true

# ---------------------------------------------------------------
# Search Services
# ---------------------------------------------------------------

# Local Search
local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1
  unescape: false
  preload: false

# ---------------------------------------------------------------
# CDN Settings
# ---------------------------------------------------------------

vendors:
  internal: local
  plugins: cdnjs
  custom_cdn_url:

# Assets
js: js
css: css
images: images
