# Site
keywords:
timezone:
description:
author: Arthur
language: zh-CN
title: "Arthur's Blog"
subtitle: 'just a blog'

# URL
permalink: :title/
permalink_defaults:
url: https://arthur63.cc/
pretty_urls:
  trailing_html: true
  trailing_index: true

# Directory
skip_render:
tag_dir: tags
i18n_dir: :lang
source_dir: source
public_dir: public
archive_dir: archives
category_dir: categories
code_dir: downloads/code

# Writing
future: true
titlecase: false
filename_case: 0
render_drafts: false
relative_link: false
default_layout: post
post_asset_folder: true
new_post_name: :title.md
external_link:
  enable: true
  field: site
  exclude: ''

# Codeblock
syntax_highlighter: prismjs

highlight:
  enable: false

prismjs:
  enable: true
  preprocess: false
  line_number: true
  line_threshold: 0
  tab_replace: '    '

# Home page setting
index_generator:
  path: ''
  per_page: 10
  order_by: -updated

# Category & Tag
tag_map:
category_map:
default_category: uncategorized

# Metadata elements
meta_generator: true

# Date / Time format
time_format: HH:mm:ss
updated_option: 'mtime'
date_format: YYYY-MM-DD

# Pagination
per_page: 10
pagination_dir: page

# Include / Exclude files
ignore:
include:
exclude:

# Theme
theme: next

# Search
search:
  field: post
  format: html
  limit: 10000
  path: search.json

# Markdown-it
markdown:
  plugins:
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-footnote
    - name: '@renbaoshuo/markdown-it-katex'
      options:
        skipDelimitersCheck: true

